### ISSUE TITLE
Handle input VCFs with duplicate variants

### ISSUE THREAD

**Issue by marcelm** [NBISweden/vcf2cytosure#13]
One of the example files has these two records (shortened):
```
4 165164576 SV_10027_1 N <IDUP> . PASS SVTYPE=IDUP;END=165273814
4 165164576 SV_10027_2 N N[4:165273814[ . PASS SVTYPE=IDUP;END=165273814
```
We should only use the one whose ID ends with `_1`.

**Comment by dnil** [comment]
Representing these correctly would be nice, but as we are not using IDUPs atm I'll close it for now. Please reopen if this changes!
