### ISSUE TITLE
Handle MIP (from v5) VCF files

### ISSUE THREAD

**Issue by dnil** [NBISweden/vcf2cytosure#16]
It would be great to produce cgh files from the standard clinical workflow on clinical genomics.

Should be pretty similar to a current FindSV output, but I'm sure there will be a few issues along the way. Here's a few I've come across:

- [x] Manta types fail on assert (e.g. <DUP:TANDEM> != SVTYPE=DUP)
- [x] optional: coverage? Easiest to enable TIDDIT coverage in the pipe? Or chanjo query?

**Comment by dnil** [comment]
First part fixed by pr #17!

**Comment by J35P312** [comment]
Good morning!
I was thinking about a general way of showing coverage based on the VCF. Maybe we can use the CN  of the format column?

**Comment by dnil** [comment]
Morning! As in on every SV, on every SNV or sampled on regular intervals and added from external program, e g TIDDIT or AMYCNE?

**Comment by J35P312** [comment]
Hello!
I'm working on this now! Ass we discussed, I will use the DP tag (per default) of the GATK vcf file to position probes where we have SNVs.

**Comment by dnil** [comment]
Fixed by #19.
