### ISSUE TITLE
Add sample FindSV and MIP VCFs for testing

### ISSUE THREAD

**Issue by dnil** [NBISweden/vcf2cytosure#25]
GIAB again?

**Comment by J35P312** [comment]
That  would be great! I have a copy of NA12878 that I can run through FindSV.
Could you run it through MIP if I move it to Rasta?

**Comment by dnil** [comment]
They are fairly big, but now available from HS on e.g. hasta as part of regular validation, say:
/home/proj/stage/rare-disease/mip/validation/191217/justhusky/analysis/justhusky/vcf2cytosure_ar

I could upload them to KI box, I suppose, or figshare perhaps?

**Comment by dnil** [comment]
Actually, we had a discussion at some point about uploading a couple of reference samples processed with MIP to figshare - see https://github.com/Clinical-Genomics/servers/issues/220. I'll close this for now, hoping that will happen soon.
