### ISSUE TITLE
design file

### ISSUE THREAD

**Issue by LaurensHannes** [NBISweden/vcf2cytosure#35]
Hello,

I've been trying to convert a whole genome sequencing vcf to cytosure format.
The data is mapped to the grch38 genome build, however i've changed the hard encoded data for hg19 to grch38. The program provides me with a cgh file containing probes however when i try to open it in cytosure it asks for a design file. Is there a way to create this?

Best regards,
Laurens

**Comment by dnil** [comment]
Dear Laurens, 

sorry for the late answer - we have been lax in watching the repo!

We like the idea of making the tool genome agnostic. A PR would be welcome; @J35P312 or I will try to provide that in a bit.. 

In the meantime, as far as I understand, Cytosure Interpret does not do much with the design file, unless you process array images or such, so this presumably more of a red tape issue. 

You could try editing the following line in your existing design file 
` <other name="genomic_build" value="hg19:GRCh37:Feb2009"/>`
to say 
 `<other name="genomic_build" value="hg38:GRCh38:Dec2013"/>`?

Optionally, editing the design file name in the CGH-template in the constants file of vcf2cytosure to point to a preexisting hg38 file? Or perhaps event to point to a hg19 design file you might have handy? 

Good luck, and thank you for trying out and improving on our tool!

// Daniel

**Comment by dnil** [comment]
Hi, we now have a hg38 pre-adapted version (0.7.0 and above). You would still need to provide/specify a design file for hg38 (could be like a default Cytosure one), but otherwise the export should work if you run `vcf2cytosure` with the `--genome 38` option. I'll close this for now, but feel free to re-open - or PR if you have adapted it already!
