### ISSUE TITLE
Generalise singularity...

### ISSUE THREAD

**Issue by dnil** [NBISweden/vcf2cytosure#43]
I could change the version number in the config, but someone (ping @J35P312) would probably still have to trigger a build? Should ideally be triggered automagically..

**Comment by dnil** [comment]
Ping @J35P312. I made a new singularity file, but this is a little silly. We could move this into Clinical Genomics and add a dockerhub integration? Or we could stick with singularity, and add e.g. https://github.com/singularityhub/github-ci.

**Comment by J35P312** [comment]
That is a good idea! I agree, the singularity file is getting a bit silly =P.
Alternatively, maybe we should use bioconda?

**Comment by dnil** [comment]
Docker is up!
