### ISSUE TITLE
Error converting TIDDIT SVs 

### ISSUE THREAD

**Issue by khurrammaqbool** [NBISweden/vcf2cytosure#53]
I used TIDDIT v3.0.0 and vcf2cytosure v0.7.1 and got the following error.

INFO: vcf2cytosure 0.7.1
[W::vcf_parse_format] FORMAT 'SR' is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'RD' is not defined in the header, assuming Type=String
Traceback (most recent call last):
  File "/opt/conda/bin/vcf2cytosure", line 8, in <module>
    sys.exit(main())
  File "/opt/vcf2cytosure/vcf2cytosure.py", line 578, in main
    height = ABERRATION_HEIGHTS[event.type]
KeyError: 'DUP:TANDEM'

**Comment by dnil** [comment]
Would also be the same for DUP:INV. Split on ':' and ignore the subtype for setting aberration height perhaps?
